# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to VPS

on:
  push:
    branches:
      - main
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: "0.131.0"
    steps:
      - uses: actions/checkout@v4
      - run: tree -L 2
      
      - name: Hugo-Site
        uses: chabad360/hugo-actions@v2
        with:
          hugoVersion: 0.131.0
      - name: Deploy to VPS
        id: deploy_theme
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-avc --delete'
          src: 'public/'
          dest: 'root@"${{secrets.SERVER_IP}}":/var/www/gabch/'
      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
